manchester_list = ["MARCUS RASHFORD","CRISTIANO RONALDO","BRUNO FERNANDES","FRED","SCOTT MCTOMINAY","JADON SANCHO","ALEX TELLES","HARRY MAGUIRE","VICTO LINDELOF","DIOGO DALOT","DAVID DE GEA","JESSE LINGARD","MARCUS RASHFORD","JADON SANCHO","ALEX TELLES","JADON SANCHO","ALEX TELLES","JADON SANCHO","ALEX TELLES","HARRY MAGUIRE","VICTO LINDELOF","DIOGO DALOT","DAVID DE GEA","JESSE LINGARD","DIOGO DALOT","DAVID DE GEA","JESSE LINGARD","MARCUS RASHFORD","JADON SANCHO","ALEX TELLES","JADON SANCHO","ALEX TELLES","JADON SANCHO","ALEX TELLES","HARRY MAGUIRE","VICTO LINDELOF","DAVID DE GEA","JESSE LINGARD","MARCUS RASHFORD","JADON SANCHO","ALEX TELLES","JADON SANCHO"]

class FindUniqueElements:
    
    def find_unique_elements(self,inputList):
        unique_elem = set(manchester_list)
        return list(unique_elem)
    
instance = FindUniqueElements()
uniq_list = instance.find_unique_elements(manchester_list)
print(uniq_list)